# Universidad Católica Luis Amigó

Curso: Fundamentos de Inteligencia Artificial

Docente: Juan Carlos Briñez de León


# Clase 11: Other classifiers

Problem:


Clasificación de variedades de flores iris.

In [10]:
#0. Importando dataset.
import pandas as pd
import numpy as np

#Cargando datos pima indians dataset
dataset = pd.read_csv(r'/content/Iris_dataset.csv')
print(dataset)
dataset = np.array(dataset)


     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [11]:
#1. Dividing dataset into input (X) and output (Y) variables
X = dataset[:,0:4]
Y = dataset[:,4]

In [12]:
#2. Discretizing the categorical data.
Y2=np.zeros((len(Y)))
for i in range(0,len(Y)):
  if Y[i]=='Iris-setosa':
     Y2[i]=1
  else:
     if Y[i]=='Iris-versicolor':
        Y2[i]=2
     else:
        Y2[i]=3

In [16]:
#3. Split input and output into training and testing sets
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test= train_test_split(X,Y2,test_size=0.2,random_state=14541)

In [17]:
#4. Data normalization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

===================================================================

In [18]:
#5. Evaluando casos mediante KNN
from sklearn.neighbors import KNeighborsClassifier
Modelo_0 = KNeighborsClassifier(3)
Modelo_0.fit(X_train, Y_train)
Y_pred_0 =Modelo_0.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_0[j])
print('')

Mostrando el Expected y predicted
1.0   1.0
2.0   2.0
2.0   2.0
1.0   1.0
3.0   3.0
2.0   2.0
2.0   2.0
1.0   1.0
1.0   1.0
3.0   3.0
1.0   1.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
2.0   2.0
3.0   3.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
2.0   2.0
1.0   1.0
2.0   2.0
3.0   3.0



In [19]:
#5_B. Calculating confusion matrix
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_0)
print(matrix)
print('')

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]



In [20]:
#5_C. calculando desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_0))

Accuracy  1.0


In [22]:
#5_D: Creating a new target
X_new = np.array([[3, 2, 1, 0.2], [  4.9, 2.2, 3.8, 1.1 ], [  5.3, 2.5, 4.6, 1.9 ]])
X_new = scaler.transform(X_new)
#Prediction of the species from the input vector
prediction_0 = Modelo_0.predict(X_new)
print("Predictions of Species are: ",prediction_0)

Predictions of Species are:  [1. 2. 3.]


================================================================

In [ ]:
#6. Evaluando casos mediante Naive Bayes
from sklearn.naive_bayes import GaussianNB
Modelo_1 = GaussianNB()
Modelo_1.fit(X_train, Y_train)
Y_pred =Modelo_1.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred[j])
print('')

Mostrando el Expected y predicted
1.0   1.0
2.0   2.0
2.0   2.0
1.0   1.0
3.0   3.0
2.0   2.0
2.0   2.0
1.0   1.0
1.0   1.0
3.0   3.0
1.0   1.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
2.0   2.0
3.0   3.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
2.0   2.0
1.0   1.0
2.0   2.0
3.0   3.0



In [ ]:
#6_B. Calculating confusion matrix
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred)
print(matrix)
print('')


[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]



In [ ]:
#6_C. calculando desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred))

Accuracy  1.0


In [ ]:
#6_D: Creating a new target
X_new = np.array([[3, 2, 1, 0.2], [  4.9, 2.2, 3.8, 1.1 ], [  5.3, 2.5, 4.6, 1.9 ]])
X_new = scaler.transform(X_new)
#Prediction of the species from the input vector
prediction = Modelo_1.predict(X_new)
print("Predictions of Species are: ",prediction)

Predictions of Species are:  [3. 3. 3.]


===============================================================

In [ ]:
#7. Evaluando casos mediante LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
Modelo_2 = LinearDiscriminantAnalysis()
Modelo_2.fit(X_train, Y_train)
Y_pred_2 =Modelo_2.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_2[j])
print('')

Mostrando el Expected y predicted
1.0   1.0
2.0   2.0
2.0   2.0
1.0   1.0
3.0   3.0
2.0   2.0
2.0   2.0
1.0   1.0
1.0   1.0
3.0   3.0
1.0   1.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
2.0   2.0
3.0   3.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
2.0   2.0
1.0   1.0
2.0   2.0
3.0   3.0



In [23]:
#7_B. Calculating confusion matrix
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_2)
print(matrix)
print('')

NameError: ignored

In [ ]:
#7_C. calculando desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_2))

Accuracy  1.0


In [ ]:
#7_D: Creating a new target
X_new = np.array([[3, 2, 1, 0.2], [  4.9, 2.2, 3.8, 1.1 ], [  5.3, 2.5, 4.6, 1.9 ]])
X_new = scaler.transform(X_new)
#Prediction of the species from the input vector
prediction = Modelo_2.predict(X_new)
print("Predictions of Species are: ",prediction)

Predictions of Species are:  [1. 3. 3.]


===============================================================

In [ ]:
#8. Evaluando casos mediante QDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
Modelo_3 = QuadraticDiscriminantAnalysis()
Modelo_3.fit(X_train, Y_train)
Y_pred_3 =Modelo_3.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_3[j])
print('')

Mostrando el Expected y predicted
1.0   1.0
2.0   2.0
2.0   2.0
1.0   1.0
3.0   3.0
2.0   2.0
2.0   2.0
1.0   1.0
1.0   1.0
3.0   3.0
1.0   1.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
2.0   2.0
3.0   3.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
2.0   2.0
1.0   1.0
2.0   2.0
3.0   3.0



In [ ]:
#8_B. Calculating confusion matrix
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_3)
print(matrix)
print('')

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]



In [ ]:
#8_C. calculando desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_3))

Accuracy  1.0


In [ ]:
#8_D: Creating a new target
X_new = np.array([[3, 2, 1, 0.2], [  4.9, 2.2, 3.8, 1.1 ], [  5.3, 2.5, 4.6, 1.9 ]])
X_new = scaler.transform(X_new)
#Prediction of the species from the input vector
prediction = Modelo_3.predict(X_new)
print("Predictions of Species are: ",prediction)

Predictions of Species are:  [3. 3. 3.]


============================================

In [ ]:
#9. Decision tree classifier
from sklearn.tree import DecisionTreeClassifier
Modelo_4 = DecisionTreeClassifier()
Modelo_4.fit(X_train, Y_train)
Y_pred_4 =Modelo_4.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_4[j])
print('')

Mostrando el Expected y predicted
1.0   1.0
2.0   2.0
2.0   2.0
1.0   1.0
3.0   3.0
2.0   2.0
2.0   2.0
1.0   1.0
1.0   1.0
3.0   3.0
1.0   1.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
2.0   2.0
3.0   3.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
2.0   2.0
1.0   1.0
2.0   2.0
3.0   3.0



In [ ]:
#9_B. Calculating confusion matrix
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_4)
print(matrix)
print('')

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]



In [ ]:
#9_C. calculando desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_4))

Accuracy  1.0


In [ ]:
#9_D: Creating a new target
X_new = np.array([[3, 2, 1, 0.2], [  4.9, 2.2, 3.8, 1.1 ], [  5.3, 2.5, 4.6, 1.9 ]])
X_new = scaler.transform(X_new)
#Prediction of the species from the input vector
prediction = Modelo_4.predict(X_new)
print("Predictions of Species are: ",prediction)

Predictions of Species are:  [3. 3. 3.]


============================================

In [ ]:
#10. SVM classifier
from sklearn.svm import SVC
Modelo_5 = SVC()
Modelo_5.fit(X_train, Y_train)
Y_pred_5 =Modelo_5.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_5[j])
print('')

Mostrando el Expected y predicted
1.0   1.0
2.0   2.0
2.0   2.0
1.0   1.0
3.0   3.0
2.0   2.0
2.0   2.0
1.0   1.0
1.0   1.0
3.0   3.0
1.0   1.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
3.0   3.0
2.0   2.0
3.0   3.0
1.0   1.0
2.0   2.0
2.0   2.0
3.0   3.0
3.0   3.0
2.0   2.0
1.0   1.0
2.0   2.0
3.0   3.0



In [ ]:
#10_B. Calculating confusion matrix
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_5)
print(matrix)
print('')

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]



In [ ]:
#10_C. calculando desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_5))

Accuracy  1.0


In [ ]:
#10_D: Creating a new target
X_new = np.array([[3, 2, 1, 0.2], [  4.9, 2.2, 3.8, 1.1 ], [  5.3, 2.5, 4.6, 1.9 ]])
X_new = scaler.transform(X_new)
#Prediction of the species from the input vector
prediction = Modelo_5.predict(X_new)
print("Predictions of Species are: ",prediction)

Predictions of Species are:  [3. 3. 3.]
