In [68]:
# 0. Importando el conjunto de datos
import pandas as pd
import numpy as np

# Cargando el dataset de la calidad de los vinos
dataset = pd.read_csv(r'/content/drogas.csv')
dataset.info()
print("==========================================")
dataset["Sex"] = dataset["Sex"].replace("F", "1")
dataset["Sex"] = dataset["Sex"].replace("M", "2")
dataset["Sex"] = dataset["Sex"].astype(np.float16)

dataset["BP"] = dataset["BP"].replace("HIGH", 1)
dataset["BP"] = dataset["BP"].replace("LOW", 2)
dataset["BP"] = dataset["BP"].replace("NORMAL", 3)
dataset["BP"] = dataset["BP"].astype(np.float16)

dataset["Cholesterol"] = dataset["Cholesterol"].replace("HIGH", 1)
dataset["Cholesterol"] = dataset["Cholesterol"].replace("LOW", 2)
dataset["Cholesterol"] = dataset["Cholesterol"].replace("NORMAL", 3)
dataset["Cholesterol"] = dataset["Cholesterol"].astype(np.float16)

dataset = np.array(dataset)
dataset.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


(200, 6)

In [69]:
#1. Diviendo el dataset en conjuntos de entrada(X) y salida(Y)
X = dataset[:,0:5]
Y = dataset[:,5]

In [70]:
#2. Discreción categorica de los datos de salida
Y2 = np.zeros((len(Y)))
for i in range(0, len(Y)):
  if Y[i]=='drugA':
     Y2[i] = 1
  elif Y[i] == 'DrugY':
     Y2[i] = 2
  elif Y[i] == 'drugX':
     Y2[i] = 3
  elif Y[i] == 'drugA':
     Y2[i] = 4
  elif Y[i] == 'drugB':
     Y2[i] = 5
  else:
     Y2[i] = 6

print(f"Tipos de droga: \n {Y}")
print("")
print(f"Tipos de droga ya categorizadas: \n{Y2}")

Tipos de droga: 
 ['DrugY' 'drugC' 'drugC' 'drugX' 'DrugY' 'drugX' 'DrugY' 'drugC' 'DrugY'
 'DrugY' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'drugX' 'drugA'
 'drugC' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'drugX' 'drugB' 'drugX' 'DrugY' 'drugX' 'drugX'
 'drugA' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugB' 'DrugY' 'drugX' 'drugX'
 'drugX' 'drugA' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY'
 'drugB' 'drugC' 'drugB' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'drugA' 'DrugY'
 'drugX' 'drugB' 'DrugY' 'drugA' 'drugX' 'DrugY' 'DrugY' 'drugB' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'DrugY' 'drugA' 'DrugY' 'drugA' 'drugX' 'drugB'
 'drugX' 'drugC' 'drugA' 'drugC' 'drugB' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'drugA' 'drugA' 'drugC' 'drugX' 'DrugY' 'drugX' 'drugX' 'DrugY'
 'drugB' 'DrugY' 'drugA' 'drugX' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugX'
 'drugX' 'drugA' 'DrugY' 'DrugY' 

In [71]:
#3. Split input and output into training and testing sets
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test= train_test_split(X,Y2,test_size=0.2,random_state=14541)

In [72]:
#4. Data normalization
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#5. Evaluando casos mediante KNN
from sklearn.neighbors import KNeighborsClassifier
Modelo_0 = KNeighborsClassifier(3)
Modelo_0.fit(X_train, Y_train)
Y_pred_0 =Modelo_0.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_0[j])
print('')

In [74]:
#5_B. Calculating confusion matrix
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_0)
print(matrix)
print('')

[[ 6  0  0  0  0]
 [ 1 13  1  1  0]
 [ 0  2  9  0  0]
 [ 1  0  0  2  0]
 [ 0  1  0  0  3]]



In [75]:
#5_C. calculando desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_0))

Accuracy  0.825
