In [1]:
# 0. Importando el conjunto de datos
import pandas as pd
import numpy as np

# Cargando el dataset de la calidad de los vinos
dataset = pd.read_csv(r'/content/winequality-red.csv')
print(dataset)

dataset = np.array(dataset)
dataset.shape

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  

(1599, 12)

In [2]:
#1. Diviendo el dataset en conjuntos de entrada(X) y salida(Y)
X = dataset[:,0:11]
Y = dataset[:,11]

In [3]:
#2. Dividiendo entre conjuntos de entrenamiento y de prueba
import sklearn
from sklearn.model_selection import train_test_split

# Verificamos el tamaño
print(len(X))
print(len(Y))

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 14541)

1599
1599


In [4]:
#3. Normalizacion de los datos
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

=============================================================

In [5]:
#4. Evaluando los vinos por medio de KNN
from sklearn.neighbors import KNeighborsClassifier

Modelo_0 = KNeighborsClassifier(3)
Modelo_0.fit(X_train, Y_train)
Y_pred_0 =Modelo_0.predict (X_test)

# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_0[j])
print('')

Mostrando el Expected y predicted
5.0   6.0
5.0   5.0
6.0   5.0
6.0   6.0
6.0   6.0
7.0   6.0
6.0   7.0
5.0   6.0
6.0   6.0
5.0   5.0
6.0   5.0
5.0   5.0
7.0   8.0
5.0   5.0
5.0   5.0
5.0   6.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   5.0
7.0   7.0
6.0   6.0
5.0   5.0
4.0   6.0
6.0   5.0
6.0   5.0
5.0   6.0
5.0   6.0
5.0   6.0
5.0   5.0
5.0   5.0
5.0   6.0
5.0   5.0
5.0   4.0
7.0   5.0
5.0   5.0
5.0   5.0
7.0   5.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   6.0
5.0   6.0
6.0   5.0
6.0   5.0
5.0   5.0
8.0   7.0
6.0   6.0
6.0   5.0
5.0   6.0
6.0   6.0
5.0   5.0
7.0   7.0
8.0   7.0
6.0   6.0
4.0   6.0
5.0   5.0
5.0   5.0
6.0   6.0
6.0   6.0
5.0   5.0
7.0   5.0
5.0   6.0
4.0   6.0
7.0   7.0
6.0   6.0
5.0   6.0
6.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   5.0
3.0   5.0
6.0   6.0
5.0   5.0
7.0   5.0
6.0   6.0
6.0   6.0
6.0   5.0
6.0   6.0
5.0   5.0
6.0   7.0
6.0   6.0
5.0   6.0
6.0   6.0
6.0   6.0
6.0   7.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   5.0
5.0   5.0
5.0   6.0
6.0   4.0
7.0   7.0
7.0   

In [6]:
#4-B. Calculando la matriz de confusion
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_0)
print(matrix)
print('')

[[ 0  1  2  0  0  0]
 [ 1  1  4  4  1  0]
 [ 0  1 90 40  1  0]
 [ 0  2 33 80  9  0]
 [ 0  0 11 15 20  1]
 [ 0  0  0  0  3  0]]



In [7]:
#4-C. Cuantificando el desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ", accuracy_score(Y_test, Y_pred_0))

Accuracy  0.596875


In [8]:
#4-D. Creando un nuevo individuo/objeto
X_new = np.array([[8.0, 0.46, 0.23, 4.5, 0.096, 34, 102, 0.9956, 3.32, 0.75, 10], [ 7.4, 0.88, 0.04, 1.9, 0.076, 11, 67, 0.997, 3.16, 0.56, 9.5 ]])
X_new = scaler.transform(X_new)

# Predeccion de la calidad del vino rojo
prediction_0 = Modelo_0.predict(X_new)
print(f"Prediccion de la calidad vino: {prediction_0}")

Prediccion de la calidad vino: [6. 5.]


=============================================================

In [9]:
#5. Evaluando los vinos por medio de Naive Bayes
from sklearn.naive_bayes import GaussianNB
Modelo_1 = GaussianNB()
Modelo_1.fit(X_train, Y_train)
Y_pred =Modelo_1.predict (X_test)

# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred[j])
print('')

Mostrando el Expected y predicted
5.0   5.0
5.0   5.0
6.0   5.0
6.0   5.0
6.0   7.0
7.0   6.0
6.0   6.0
5.0   7.0
6.0   7.0
5.0   6.0
6.0   5.0
5.0   5.0
7.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
6.0   5.0
5.0   5.0
7.0   7.0
6.0   5.0
5.0   5.0
4.0   4.0
6.0   6.0
6.0   5.0
5.0   6.0
5.0   5.0
5.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
7.0   5.0
5.0   5.0
5.0   6.0
7.0   5.0
6.0   7.0
5.0   5.0
6.0   7.0
5.0   5.0
5.0   6.0
6.0   6.0
6.0   5.0
5.0   5.0
8.0   7.0
6.0   6.0
6.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   7.0
8.0   7.0
6.0   6.0
4.0   5.0
5.0   5.0
5.0   5.0
6.0   5.0
6.0   5.0
5.0   5.0
7.0   6.0
5.0   5.0
4.0   5.0
7.0   7.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   5.0
5.0   5.0
6.0   7.0
5.0   5.0
7.0   6.0
3.0   5.0
6.0   7.0
5.0   5.0
7.0   6.0
6.0   6.0
6.0   6.0
6.0   5.0
6.0   7.0
5.0   5.0
6.0   7.0
6.0   7.0
5.0   5.0
6.0   7.0
6.0   6.0
6.0   7.0
6.0   5.0
5.0   5.0
6.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
7.0   7.0
7.0   

In [10]:
#5-B. Calculando la matriz de confusion
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred)
print(matrix)
print('')

[[ 0  1  2  0  0  0]
 [ 0  2  6  3  0  0]
 [ 0  6 95 22  9  0]
 [ 0  1 41 61 20  1]
 [ 0  0  4 18 25  0]
 [ 0  0  0  0  3  0]]



In [11]:
#5-C. Cuantificando el desempeño (Exactitud)
from sklearn.metrics import accuracy_score, precision_score
print("Accuracy ", accuracy_score(Y_test, Y_pred))

Accuracy  0.571875


In [12]:
#5-D. Creando un nuevo individuo/objeto
X_new = np.array([[8.0, 0.46, 0.23, 4.5, 0.096, 34, 102, 0.9956, 3.32, 0.75, 10], [ 7.4, 0.88, 0.04, 1.9, 0.076, 11, 67, 0.997, 3.16, 0.56, 9.5 ]])
X_new = scaler.transform(X_new)

# Predeccion de la calidad del vino rojo
prediction = Modelo_1.predict(X_new)
print(f"Prediccion de la calidad vino: {prediction}")

Prediccion de la calidad vino: [5. 5.]


========================================================================

In [13]:
#6. Evaluando los vinos por medio de LDA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

Modelo_2 = LinearDiscriminantAnalysis()
Modelo_2.fit(X_train, Y_train)
Y_pred_2 =Modelo_2.predict (X_test)

# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_2[j])
print('')

Mostrando el Expected y predicted
5.0   5.0
5.0   5.0
6.0   5.0
6.0   5.0
6.0   6.0
7.0   6.0
6.0   6.0
5.0   7.0
6.0   7.0
5.0   5.0
6.0   5.0
5.0   5.0
7.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   7.0
6.0   5.0
5.0   5.0
4.0   4.0
6.0   5.0
6.0   5.0
5.0   6.0
5.0   5.0
5.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
7.0   5.0
5.0   5.0
5.0   6.0
7.0   6.0
6.0   6.0
5.0   5.0
6.0   7.0
5.0   5.0
5.0   6.0
6.0   5.0
6.0   5.0
5.0   5.0
8.0   7.0
6.0   6.0
6.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   7.0
8.0   7.0
6.0   6.0
4.0   5.0
5.0   5.0
5.0   5.0
6.0   5.0
6.0   5.0
5.0   5.0
7.0   6.0
5.0   5.0
4.0   5.0
7.0   7.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   5.0
5.0   5.0
6.0   7.0
5.0   5.0
7.0   6.0
3.0   5.0
6.0   6.0
5.0   5.0
7.0   6.0
6.0   5.0
6.0   6.0
6.0   6.0
6.0   6.0
5.0   5.0
6.0   8.0
6.0   6.0
5.0   5.0
6.0   7.0
6.0   6.0
6.0   7.0
6.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
7.0   7.0
7.0   

In [14]:
#6-B. Calculando la matriz de confusion
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_2)
print(matrix)
print('')

[[  1   0   1   1   0   0]
 [  0   2   6   2   1   0]
 [  0   0 101  29   2   0]
 [  0   1  44  70   8   1]
 [  0   0   4  25  18   0]
 [  0   0   0   0   3   0]]



In [15]:
#6-C. Cuantificando el desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_2))

Accuracy  0.6


In [16]:
#6-D. Creando un nuevo individuo/objeto
X_new = np.array([[8.0, 0.46, 0.23, 4.5, 0.096, 34, 102, 0.9956, 3.32, 0.75, 10], [ 7.4, 0.88, 0.04, 1.9, 0.076, 11, 67, 0.997, 3.16, 0.56, 9.5 ]])
X_new = scaler.transform(X_new)
# Predeccion de la calidad del vino rojo
prediction = Modelo_2.predict(X_new)
print(f"Prediccion de la calidad vino: {prediction}")

Prediccion de la calidad vino: [5. 5.]


=============================================================

In [17]:
#7. Evaluando los vinos por medio de QDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
Modelo_3 = QuadraticDiscriminantAnalysis()
Modelo_3.fit(X_train, Y_train)
Y_pred_3 =Modelo_3.predict (X_test)

# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_3[j])
print('')

Mostrando el Expected y predicted
5.0   5.0
5.0   6.0
6.0   6.0
6.0   5.0
6.0   6.0
7.0   6.0
6.0   7.0
5.0   6.0
6.0   7.0
5.0   5.0
6.0   4.0
5.0   5.0
7.0   8.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
6.0   5.0
5.0   5.0
7.0   7.0
6.0   5.0
5.0   5.0
4.0   5.0
6.0   6.0
6.0   5.0
5.0   6.0
5.0   5.0
5.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
7.0   5.0
5.0   6.0
5.0   6.0
7.0   6.0
6.0   6.0
5.0   5.0
6.0   7.0
5.0   5.0
5.0   6.0
6.0   6.0
6.0   5.0
5.0   5.0
8.0   7.0
6.0   6.0
6.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   7.0
8.0   7.0
6.0   6.0
4.0   5.0
5.0   5.0
5.0   5.0
6.0   5.0
6.0   5.0
5.0   5.0
7.0   6.0
5.0   5.0
4.0   6.0
7.0   7.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   5.0
5.0   5.0
6.0   8.0
5.0   5.0
7.0   6.0
3.0   5.0
6.0   7.0
5.0   6.0
7.0   6.0
6.0   5.0
6.0   6.0
6.0   5.0
6.0   6.0
5.0   5.0
6.0   8.0
6.0   6.0
5.0   5.0
6.0   6.0
6.0   6.0
6.0   7.0
6.0   5.0
5.0   6.0
6.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
7.0   7.0
7.0   

/usr/local/lib/python3.7/dist-packages/sklearn/discriminant_analysis.py:878: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [18]:
#7-B. Calculando la matriz de confusion
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_3)
print(matrix)
print('')

[[ 0  1  1  1  0  0]
 [ 0  1  7  2  1  0]
 [ 0  4 88 37  3  0]
 [ 0  2 41 66 13  2]
 [ 0  0  2 22 18  5]
 [ 0  0  0  0  3  0]]



In [19]:
#7-C. Cuantificando el desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_3))

Accuracy  0.540625


In [20]:
#7-D. Creando un nuevo individuo/objeto
X_new = np.array([[8.0, 0.46, 0.23, 4.5, 0.096, 34, 102, 0.9956, 3.32, 0.75, 10], [ 7.4, 0.88, 0.04, 1.9, 0.076, 11, 67, 0.997, 3.16, 0.56, 9.5 ]])
X_new = scaler.transform(X_new)
# Predeccion de la calidad del vino rojo
prediction = Modelo_3.predict(X_new)
print(f"Prediccion de la calidad vino: {prediction}")

Prediccion de la calidad vino: [6. 5.]


==========================================================

In [21]:
#8. Evaluando los vinos por medio de arbol de decisiones
from sklearn.tree import DecisionTreeClassifier
Modelo_4 = DecisionTreeClassifier()
Modelo_4.fit(X_train, Y_train)
Y_pred_4 =Modelo_4.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_4[j])
print('')

Mostrando el Expected y predicted
5.0   7.0
5.0   5.0
6.0   5.0
6.0   6.0
6.0   6.0
7.0   7.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   5.0
6.0   6.0
5.0   6.0
7.0   7.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   7.0
6.0   6.0
5.0   5.0
4.0   6.0
6.0   6.0
6.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   4.0
7.0   5.0
5.0   5.0
5.0   5.0
7.0   7.0
6.0   6.0
5.0   5.0
6.0   6.0
5.0   6.0
5.0   5.0
6.0   6.0
6.0   5.0
5.0   5.0
8.0   7.0
6.0   7.0
6.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   7.0
8.0   6.0
6.0   6.0
4.0   6.0
5.0   5.0
5.0   5.0
6.0   5.0
6.0   6.0
5.0   5.0
7.0   7.0
5.0   5.0
4.0   5.0
7.0   7.0
6.0   6.0
5.0   5.0
6.0   6.0
5.0   5.0
5.0   5.0
6.0   8.0
5.0   5.0
7.0   7.0
3.0   4.0
6.0   6.0
5.0   5.0
7.0   7.0
6.0   5.0
6.0   6.0
6.0   6.0
6.0   6.0
5.0   5.0
6.0   7.0
6.0   6.0
5.0   5.0
6.0   7.0
6.0   6.0
6.0   7.0
6.0   5.0
5.0   6.0
6.0   5.0
5.0   5.0
5.0   5.0
5.0   6.0
6.0   5.0
7.0   6.0
7.0   

In [22]:
#8-B. Calculando la matriz de confusion
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_4)
print(matrix)
print('')

[[  0   1   2   0   0   0]
 [  0   2   5   3   1   0]
 [  0   4 102  23   3   0]
 [  0   1  31  75  16   1]
 [  0   0   4  19  20   4]
 [  0   0   0   2   1   0]]



In [23]:
#8-C. Cuantificando el desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_4))

Accuracy  0.621875


In [24]:
#8-D. Creando un nuevo individuo/objeto
X_new = np.array([[8.0, 0.46, 0.23, 4.5, 0.096, 34, 102, 0.9956, 3.32, 0.75, 10], [ 7.4, 0.88, 0.04, 1.9, 0.076, 11, 67, 0.997, 3.16, 0.56, 9.5 ]])
X_new = scaler.transform(X_new)
# Predeccion de la calidad del vino rojo
prediction = Modelo_4.predict(X_new)
print(f"Prediccion de la calidad vino: {prediction}")

Prediccion de la calidad vino: [5. 5.]


=========================================================

In [25]:
#9. Evaluando los vinos por medio de SVM
from sklearn.svm import SVC
Modelo_5 = SVC()
Modelo_5.fit(X_train, Y_train)
Y_pred_5 =Modelo_5.predict (X_test)
# Graficando resultados
print('Mostrando el Expected y predicted')
for j in range(0,len(Y_test)): 
  print (Y_test[j],' ',Y_pred_5[j])
print('')

Mostrando el Expected y predicted
5.0   5.0
5.0   5.0
6.0   5.0
6.0   5.0
6.0   6.0
7.0   6.0
6.0   6.0
5.0   6.0
6.0   7.0
5.0   5.0
6.0   5.0
5.0   5.0
7.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
6.0   5.0
5.0   5.0
7.0   6.0
6.0   5.0
5.0   5.0
4.0   5.0
6.0   5.0
6.0   5.0
5.0   6.0
5.0   5.0
5.0   6.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
7.0   5.0
5.0   5.0
5.0   6.0
7.0   5.0
6.0   6.0
5.0   5.0
6.0   7.0
5.0   5.0
5.0   6.0
6.0   5.0
6.0   5.0
5.0   5.0
8.0   7.0
6.0   6.0
6.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   6.0
8.0   6.0
6.0   6.0
4.0   5.0
5.0   5.0
5.0   5.0
6.0   5.0
6.0   5.0
5.0   5.0
7.0   6.0
5.0   5.0
4.0   6.0
7.0   7.0
6.0   6.0
5.0   6.0
6.0   6.0
5.0   5.0
5.0   5.0
6.0   6.0
5.0   5.0
7.0   6.0
3.0   5.0
6.0   6.0
5.0   5.0
7.0   6.0
6.0   5.0
6.0   6.0
6.0   5.0
6.0   7.0
5.0   5.0
6.0   7.0
6.0   6.0
5.0   5.0
6.0   6.0
6.0   6.0
6.0   6.0
6.0   5.0
5.0   5.0
6.0   5.0
5.0   5.0
5.0   5.0
5.0   5.0
6.0   6.0
7.0   7.0
7.0   

In [26]:
#9-B. Calculando la matriz de confusion
import sklearn
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(Y_test, Y_pred_5)
print(matrix)
print('')

[[  0   0   2   1   0   0]
 [  0   0   8   2   1   0]
 [  0   0 105  27   0   0]
 [  0   0  47  72   5   0]
 [  0   0   4  36   7   0]
 [  0   0   0   2   1   0]]



In [27]:
#9-C. Cuantificando el desempeño (Exactitud)
from sklearn.metrics import accuracy_score,precision_score
print("Accuracy ",accuracy_score(Y_test, Y_pred_5))

Accuracy  0.575


In [28]:
#9-D. Creando un nuevo individuo/objeto
X_new = np.array([[8.0, 0.46, 0.23, 4.5, 0.096, 34, 102, 0.9956, 3.32, 0.75, 10], [ 7.4, 0.88, 0.04, 1.9, 0.076, 11, 67, 0.997, 3.16, 0.56, 9.5 ]])
X_new = scaler.transform(X_new)
# Predeccion de la calidad del vino rojo
prediction = Modelo_5.predict(X_new)
print(f"Prediccion de la calidad vino: {prediction}")

Prediccion de la calidad vino: [5. 5.]
